project:
  type: website

website:
  title: "DACSS603Final"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Codebook
      - href: data_cleaning.qmd
        text: Data Cleaning
        
bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

